### ISSUE TITLE
Not a java programmer :(

### ISSUE THREAD

**Issue by robin-ds** [joeferner/stm32cubemx-patch#1]
Running 4.10.1 and seeing the same problem as you and everyone else but to fix it I'm lost! Unfortunately, 40 years of assembler and 'C' experience doesn't help with the vocabulary of java.

Unpack - this is a basic unzip into a working directory - yes?
Run `java com.fernsroth.stm32cubmxpatch.Patch <gpio dir>`
 I get the following error
robin@robin-desktop:~/src/stm32cubemx-patch/src/main/java$ java com.fernsroth.stm32cubmxpatch.Patch ~/tmp/gpio
Error: Could not find or load main class com.fernsroth.stm32cubmxpatch.Patch

Repackage `gpio.jar` - no idea what utility I'd use to do this.

A few crumbs on how to proceed would be great

**Comment by joeferner** [comment]
It was a little too late at night when I wrote those instructions. I've updated them with something a little better. Let me know if you get it working.

**Comment by robin-ds** [comment]
Perfect - many thanks for taking the time to help out an old man!!
